apiVersion: apps/v1
kind: Deployment
metadata:
  name: devopsagent-deployment
  labels:
    app: devopsagent
  namespace: devops
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: devopsagent
  template:
    metadata:
      labels:
        app: devopsagent
    spec:
      containers:
      - name: kubepodcreation
        image: myazcregistry.azurecr.io/devopsagent:u22
        env:
          - name: AZP_URL
            valueFrom:
              secretKeyRef:
                name: devops-agent
                key: AZP_URL
          - name: AZP_TOKEN
            valueFrom:
              secretKeyRef:
                name: devops-agent
                key: AZP_TOKEN
          - name: AZP_POOL
            valueFrom:
              secretKeyRef:
                name: devops-agent
                key: AZP_POOL

        volumeMounts:
        - mountPath: /var/run/docker.sock
          name: docker-volume
      volumes:
      - name: docker-volume
        hostPath:
          path: /var/run/docker.sock
